/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: LibCarla/source/carla/ros2/dds/cyclonedds/types/AccelWithCovarianceStamped.h
  Source: /home/taiga/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/AccelWithCovarianceStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCESTAMPED_H
#define DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCESTAMPED_H

#include "Header.h"

#include "AccelWithCovariance.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_AccelWithCovarianceStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_AccelWithCovariance accel;
} geometry_msgs_msg_AccelWithCovarianceStamped;

extern const dds_topic_descriptor_t geometry_msgs_msg_AccelWithCovarianceStamped_desc;

#define geometry_msgs_msg_AccelWithCovarianceStamped__alloc() \
((geometry_msgs_msg_AccelWithCovarianceStamped*) dds_alloc (sizeof (geometry_msgs_msg_AccelWithCovarianceStamped)));

#define geometry_msgs_msg_AccelWithCovarianceStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_AccelWithCovarianceStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCESTAMPED_H */
