/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: LibCarla/source/carla/ros2/dds/cyclonedds/types/Accel.h
  Source: /home/taiga/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Accel.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCEL_H
#define DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCEL_H

#include "Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Accel
{
  struct geometry_msgs_msg_Vector3 linear;
  struct geometry_msgs_msg_Vector3 angular;
} geometry_msgs_msg_Accel;

extern const dds_topic_descriptor_t geometry_msgs_msg_Accel_desc;

#define geometry_msgs_msg_Accel__alloc() \
((geometry_msgs_msg_Accel*) dds_alloc (sizeof (geometry_msgs_msg_Accel)));

#define geometry_msgs_msg_Accel_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Accel_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCEL_H */
