/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: LibCarla/source/carla/ros2/dds/cyclonedds/types/AccelWithCovariance.h
  Source: /home/taiga/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/AccelWithCovariance.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCE_H
#define DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCE_H

#include "Accel.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_AccelWithCovariance
{
  struct geometry_msgs_msg_Accel accel;
  double covariance[36];
} geometry_msgs_msg_AccelWithCovariance;

extern const dds_topic_descriptor_t geometry_msgs_msg_AccelWithCovariance_desc;

#define geometry_msgs_msg_AccelWithCovariance__alloc() \
((geometry_msgs_msg_AccelWithCovariance*) dds_alloc (sizeof (geometry_msgs_msg_AccelWithCovariance)));

#define geometry_msgs_msg_AccelWithCovariance_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_AccelWithCovariance_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ACCELWITHCOVARIANCE_H */
